development: &default
  encoding: utf8
  adapter: postgresql
  min_messages: warning
  timeout: 5000
  host: localhost
  port: 5432
  username: <%= ENV.fetch('AACT_DB_SUPER_USERNAME', 'ctti') %>
  password: <%= ENV.fetch('AACT_PASSWORD', '') %>
  database: <%= ENV.fetch('AACT_ADMIN_DATABASE_NAME', 'aact_admin') %>

test:
  encoding: utf8
  adapter: postgresql
  host: localhost
  port: 5432
  username: <%= ENV.fetch('AACT_USERNAME', 'ctti') %>
  password: <%= ENV.fetch('AACT_PASSWORD', '') %>
  database: aact_admin_test
  # database: aact_admin_test

production: &deploy
  encoding: utf8
  adapter: postgresql
  min_messages: warning
  timeout: 5000
  # host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  # port: <%= ENV.fetch('DB_PORT', 5432) %>
  # username: <%= ENV.fetch('DB_USER', 'ctti') %>
  # password: <%= ENV['DB_PASS'] %>
  # database: <%= ENV['DB_NAME'] %>
  url:  <%= "postgres://#{ENV.fetch('AACT_DB_SUPER_USERNAME','ctti')}@localhost:5432/#{ENV.fetch('AACT_ADMIN_DATABASE_NAME','aact_admin')}" %>
